services:
  nlp:
    image: "mcr.microsoft.com/devcontainers/python:1-3.10-bullseye"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    ports:
      - ${NLP_PORT}:${NLP_PORT}
    environment:
      NLP_PORT: ${NLP_PORT}
  app:
    image: "mcr.microsoft.com/devcontainers/dotnet:1-8.0"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: ${POSTGRES_USER}
      DB_NAME: ${POSTGRES_DB_NAME}
      DB_PORT: ${POSTGRES_PORT}
      NLP_HOST: ${NLP_HOST}
      NLP_PORT: ${NLP_PORT}
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8080:8978
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace

volumes:
  postgres-data:
  cloudbeaver-data:
