services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    ports:
      - 8080:8978
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
  recipe_nlp:
    build:
      context: ./recipe_nlp
    ports:
      - 8000:80
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./storage:/mnt/data
    command: minio server --console-address ":9090" /mnt/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
