services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file: "db.env"
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  cloudbeaver:
    image: dbeaver/cloudbeaver
    ports:
      - 8080:8978
    volumes:
      - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
  recipe_nlp:
    build:
      context: ./recipe_nlp
    ports:
      - 8000:80
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./storage:/mnt/data
    env_file: "storage.env"
    command: minio server --console-address ":9090" /mnt/data
