version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass1




#  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  # -p 6831:6831/udp \
  # -p 6832:6832/udp \
  # -p 5778:5778 \
  # -p 16686:16686 \
  # -p 4317:4317 \
  # -p 4318:4318 \
  # -p 14250:14250 \
  # -p 14268:14268 \
  # -p 14269:14269 \
  # -p 9411:9411 \
  # jaegertracing/all-in-one:1.60