version: "3.8"

services:
  # app: build
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  # dbeaver:
  #   image: dbeaver/cloudbeaver
  #   ports:
  #     - 8080:8978
  #   volumes:
  #     - ./cloudbeaver/workspace:/opt/cloudbeaver/workspace
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 8000:80
    volumes:
      - ./backend/pgadmin/config:/var/lib/pgadmin
      - ./backend/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password1
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./backend/redis:/data
  recipe_nlp:
    build:
      context: ./backend/recipe_nlp
    ports:
      - 80:80
  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ./backend/storage:/mnt/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: minio server --console-address ":9090" /mnt/data


#  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  # -p 6831:6831/udp \
  # -p 6832:6832/udp \
  # -p 5778:5778 \
  # -p 16686:16686 \
  # -p 4317:4317 \
  # -p 4318:4318 \
  # -p 14250:14250 \
  # -p 14268:14268 \
  # -p 14269:14269 \
  # -p 9411:9411 \
  # jaegertracing/all-in-one:1.60
