import { builder } from "@/graphql/builder.js";

import "@/graphql/schemas/recipe/CategorySchema.js";
import "@/graphql/schemas/recipe/CourseSchema.js";
import "@/graphql/schemas/recipe/CuisineSchema.js";
import "@/graphql/schemas/common/EnumSchema.js";
import "@/graphql/schemas/ingredient/ExpirationRuleSchema.js";
import "@/graphql/schemas/receipt/GroceryStoreSchema.js";
import "@/graphql/schemas/nutrition/NutrientRankSchema.js";
import "@/graphql/schemas/nutrition/NutrientTargetSchema.js";
import "@/graphql/schemas/receipt/ReceiptLineSchema.js";
import "@/graphql/schemas/recipe/RecipeIngredientSchema.js";
import "@/graphql/schemas/ingredient/IngredientCategorySchema.js";
import "@/graphql/schemas/ingredient/IngredientPrice.js";
import "@/graphql/schemas/ingredient/IngredientSchema.js";
import "@/graphql/schemas/mealplan/MealPlanIngredientsSchema.js";
import "@/graphql/schemas/mealplan/MealPlanRecipeSchema.js";
import "@/graphql/schemas/mealplan/MealplanSchema.js";
import "@/graphql/schemas/mealplan/MealPlanServingsSchema.js";
import "@/graphql/schemas/common/MeasurementUnitSchema.js";
import "@/graphql/schemas/nutrition/NutrientSchema.js";
import "@/graphql/schemas/nutrition/NutritionLabelSchema.js";
import "@/graphql/schemas/common/PhotoSchema.js";
import "@/graphql/schemas/receipt/ReceiptSchema.js";
import "@/graphql/schemas/recipe/RecipeSchema.js";
import "@/graphql/schemas/user/UserSchema.js";
import "@/graphql/schemas/common/Pagination.js";
import "@/graphql/schemas/nutrition/MacroSchema.js";
import "@/graphql/schemas/recipe/RecipeIngredientGroupSchema.js";
import "@/graphql/schemas/recipe/RecipeSearchSchema.js";

export const schema = builder.toSchema();
