# Use Node.js base image
FROM node:22-alpine

ENV NODE_ENV=development
# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json  ./

RUN npm install

# Copy all source code
COPY . .

RUN npx prisma generate


# Expose port (optional, depends on your app)
EXPOSE 3025

# Command to run the application
CMD ["./start.sh"]
