import '@/presentation/schemas/recipe/CategorySchema.js';
import '@/presentation/schemas/recipe/CourseSchema.js';
import '@/presentation/schemas/recipe/CuisineSchema.js';
import '@/presentation/schemas/common/EnumSchema.js';
import '@/presentation/schemas/ingredient/ExpirationRuleSchema.js';
import '@/presentation/schemas/receipt/GroceryStoreSchema.js';
import '@/presentation/schemas/nutrition/NutrientRankSchema.js';
import '@/presentation/schemas/nutrition/NutrientTargetSchema.js';
import '@/presentation/schemas/receipt/ReceiptLineSchema.js';
import '@/presentation/schemas/recipe/RecipeIngredientSchema.js';
import '@/presentation/schemas/ingredient/IngredientCategorySchema.js';
import '@/presentation/schemas/ingredient/IngredientPriceSchema.js';
import '@/presentation/schemas/ingredient/IngredientSchema.js';
import '@/presentation/schemas/mealplan/MealPlanIngredientsSchema.js';
import '@/presentation/schemas/mealplan/MealPlanRecipeSchema.js';
import '@/presentation/schemas/mealplan/MealplanSchema.js';
import '@/presentation/schemas/mealplan/MealPlanServingsSchema.js';
import '@/presentation/schemas/common/MeasurementUnitSchema.js';
import '@/presentation/schemas/nutrition/NutrientSchema.js';
import '@/presentation/schemas/nutrition/NutritionLabelSchema.js';
import '@/presentation/schemas/common/PhotoSchema.js';
import '@/presentation/schemas/receipt/ReceiptSchema.js';
import '@/presentation/schemas/recipe/RecipeSchema.js';
import '@/presentation/schemas/user/UserSchema.js';
import '@/presentation/schemas/common/Pagination.js';
import '@/presentation/schemas/recipe/RecipeIngredientGroupSchema.js';
import '@/presentation/schemas/recipe/RecipeSearchSchema.js';

import { builder } from '@/presentation/builder.js';

export const schema = builder.toSchema();
